### ISSUE TITLE
Module update

### ISSUE THREAD

**Issue by SalahNasir** [SalahNasir/xboxheroo#3]
Hey!

Now we have released version 1.0.6 of the module easy mass order actions which should have solved the problem, you can update by writing in the terminal:

composer update media strategy / module-easymassorderactions

Then you need to run the usual commands:
bin / magento maintenance: enable && bin / magento setup: upgrade && bin / magento setup: di: compile && bin / magento setup: static-content: deploy && bin / magento maintenance: disable

**Comment by vinojkarunarathne** [comment]
Hi @SalahNasir , 

Module Update is done.
